### ISSUE TITLE
One publication correction

### ISSUE THREAD

**Issue by zzh-tech** [subeeshvasu/Awesome-Deblurring#11]
Hi, thank you so much for the awesome summary!
We have upgraded and released the real video deblurring dataset [BSD](https://github.com/zzh-tech/ESTRNN) (more blur intensity and motion pattern settings, and better design of beam-splitter acquisition system).
So, could you please also put the following item:
2020 | ECCV | Efficient Spatio-Temporal Recurrent Neural Network for Video Deblurring | Code
-- | -- | -- | --

in the following field:

**Benchmark Datasets on Motion Deblurring**

Thank you :)

**Comment by subeeshvasu** [comment]
Done. :)
