### ISSUE TITLE
Adding pmapper

### ISSUE THREAD

**Issue by brandondube** [subeeshvasu/Awesome-Deblurring#18]
Hello,

You might consider adding [pmapper](https://github.com/nasa-jpl/pmapper), an implementation of PMAP we have created at JPL.  A relevant citation would be [Multiframe Restoration Methods for Image Synthesis and Recovery, Joseph J. Green, Univ. of Arizona, PhD thesis](https://repository.arizona.edu/handle/10150/284110)

Cheers
-Brandon

**Comment by subeeshvasu** [comment]
Done. :)
