### ISSUE TITLE
[Mis-categorized Non-blind as Blind] Deep Plug-And-Play Super-Resolution for Arbitrary Blur Kernels

### ISSUE THREAD

**Issue by zikuicai** [subeeshvasu/Awesome-Deblurring#20]
Paper *Deep Plug-And-Play Super-Resolution for Arbitrary Blur Kernels* / DPSR is non-blind model-based SISR method which assumes the blur kernel is known.

https://github.com/cszn/DPSR/issues/2

**Comment by subeeshvasu** [comment]
Corrected. :)
