### ISSUE TITLE
Is there any paper talking about RAW image/video deblurring? Thanks (RAM image instead of RGB image).

### ISSUE THREAD

**Issue by zsbluesky** [subeeshvasu/Awesome-Deblurring#24]
Is there any paper talking about RAW image/video deblurring? Thanks (RAM image instead of RGB image).

**Comment by subeeshvasu** [comment]
I haven't came across any, but there could be such papers that I am not aware of.

**Comment by zsbluesky** [comment]
Here's one, Raw Image Deblurring. I think there should be more.
