### ISSUE TITLE
Two possible additions

### ISSUE THREAD

**Issue by fayolle** [subeeshvasu/Awesome-Deblurring#32]
@subeeshvasu This is a very useful list. 
I would like to propose two additions, if you allow me: 
- [Reverse image filtering with clean and noisy filters](https://link.springer.com/article/10.1007/s11760-022-02236-w) with code available [here](https://github.com/fayolle/clean_noisy_defilter)
- [Black-box image deblurring and defiltering](https://www.sciencedirect.com/science/article/pii/S0923596522001242) with code available [here (MATLAB)](https://github.com/fayolle/bbDeblur) and [here (Python)](https://github.com/fayolle/bbDeblur_py)

They would belong to the category 'non-blind' (strictly speaking 'semi-blind'). These are non-DL methods.

**Comment by subeeshvasu** [comment]
Done. Thank You. Next time, feel free to raise a PR. :)
