### ISSUE TITLE
Some consulting

### ISSUE THREAD

**Issue by Redamancy0222** [subeeshvasu/Awesome-Deblurring#36]
Hello, first of all, thank you for your efforts to collect and integrate resources. Will the latest articles on non-DL and DL image deblurring be updated？

**Comment by subeeshvasu** [comment]
@Redamancy0222 Yes, depending on when I get time for that. Thanks for the understanding. Always welcome to raise a PR with latest papers.

**Comment by subeeshvasu** [comment]
Have updated with 2023 papers
