### ISSUE TITLE
Request for correction

### ISSUE THREAD

**Issue by Drug1996** [subeeshvasu/Awesome-Deblurring#5]
Sorry, the paper link to our project is wrong.
(Multi-image/Video)-Motion-Deblurring:
Spatio-Temporal Efficient Recurrent Neural Network for Video Deblurring (ECCV 2020)

The correct one is:
Efficient Spatio-Temporal Recurrent Neural Network for Video Deblurring
https://www.ecva.net/papers/eccv_2020/papers_ECCV/html/5116_ECCV_2020_paper.php

And the code is available now as follows:
https://github.com/zzh-tech/ESTRNN

**Comment by subeeshvasu** [comment]
Done.

:)

**Comment by Drug1996** [comment]
Thanks!

:)
