### ISSUE TITLE
what does "non-DL" or "DL" mean?

### ISSUE THREAD

**Issue by suiyizhao** [subeeshvasu/Awesome-Deblurring#6]

**Comment by D-l-z** [comment]
DL：deblurring method with deep learningnon—DL：the opposite。-------- 原始邮件 --------发件人： suiyizhao <notifications@github.com>日期： 2020年11月12日周四 14:32收件人： subeeshvasu/Awesome-Deblurring <Awesome-Deblurring@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [subeeshvasu/Awesome-Deblurring] what does "non-DL" or "DL" mean? (#6)

**Comment by suiyizhao** [comment]
Thanks.

**Comment by subeeshvasu** [comment]
Since there are too many papers on deep learning (DL) and non-deep learning (non-DL) sides of single image motion deblurring, I divided them into two. I have now mentioned the abbreviations at the bottom. :)
