### ISSUE TITLE
Two publication corrections

### ISSUE THREAD

**Issue by huiwong96** [subeeshvasu/Awesome-Deblurring#8]
The paper ‘‘Convolutional neural networks for direct text deblurring ’’ and ''Blind image deconvolution using deep generative priors'' were accepted by bmvc'15 and bmvc'19 respectively.
see:
http://www.bmva.org/bmvc/2015/papers/paper006/index.html
https://bmvc2019.org/wp-content/uploads/papers/1042-paper.pdf

**Comment by subeeshvasu** [comment]
Done. :)
