### ISSUE TITLE
Two publication modified

### ISSUE THREAD

**Issue by ysnan** [subeeshvasu/Awesome-Deblurring#9]
Hi Vasu, please help to change the following publications accordingly.

(1) For "Variational-EM-Based Deep Learning for Noise-Blind Image Deblurring", please change the paper link to  "https://github.com/ysnan/VEM-NBD/blob/master/paper/vem_deconv.pdf" as this is the newest version and add the project page  with link "https://github.com/ysnan/VEM-NBD"

(2) For "Deep Learning for Handling Kernel/model Uncertainty in Image Deconvolution", please change the paper link to “https://github.com/ysnan/NBD_KerUnc/blob/master/paper/kn.pdf” and add the project page with link "https://github.com/ysnan/NBD_KerUnc"

I would also like to express my gratitude for setting up and maintaining this page for the collection of deblurring papers. It helps me a lot.

**Comment by subeeshvasu** [comment]
Thanks a lot for the updates. :)
